version: '3'

services:
  app:
    build: .
    ports:
      - "${PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/banking-ledger
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=${PORT}

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: